Bump versions.kotlin from 1.3.70-eap-184 to 1.3.70-eap-274 (#184)
Bumps `versions.kotlin` from 1.3.70-eap-184 to 1.3.70-eap-274.
Updates `kotlin-gradle-plugin` from 1.3.70-eap-184 to 1.3.70-eap-274
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/JetBrains/kotlin/releases">kotlin-gradle-plugin's releases</a>.</em></p>
<blockquote>
<h2>Kotlin 1.3.70 EAP 3</h2>
<h3>Compiler</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-31411"><code>KT-31411</code></a> Support mode of compiler where it analyses source-set as platform one, but produces only metadata for that specific source-set</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-32372"><code>KT-32372</code></a> Type inference errors in IDE</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-33542"><code>KT-33542</code></a> Compilation failed with &quot;AssertionError: Suspend functions may be called either as suspension points or from another suspend function&quot;</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-33544"><code>KT-33544</code></a> &quot;UnsupportedOperationException: no descriptor for type constructor of TypeVariable(R)?&quot; with BuilderInference and elvis operator</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-36297"><code>KT-36297</code></a> NI: ClassNotFoundException: compiler emits reference to nonexisting class for code with nested inline lambdas</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-36719"><code>KT-36719</code></a> Enable new inference in IDE since 1.3.70</li>
</ul>
<h3>IDE</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-33820"><code>KT-33820</code></a> Stop using com.intellij.codeInsight.AnnotationUtil#isJetbrainsAnnotation</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-33846"><code>KT-33846</code></a> Stop using com.intellij.openapi.vfs.newvfs.BulkFileListener.Adapter</li>
</ul>
<h3>IDE. Completion</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-36306"><code>KT-36306</code></a> Code completion inlines content of FQN class if completion called in string</li>
</ul>
<h3>IDE. Debugger</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-16277"><code>KT-16277</code></a> Can't set breakpoint for object construction</li>
</ul>
<h3>IDE. Inspections and Intentions</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-33771"><code>KT-33771</code></a> False positive &quot;Redundant Companion reference&quot; with Java synthetic property and same-named object property</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-36307"><code>KT-36307</code></a> False positive &quot;Remove redundant '.let' call&quot; for nested lambda change scope reference</li>
</ul>
<h3>IDE. Multiplatform</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-33321"><code>KT-33321</code></a> In IDE, actuals of intermediate test source set are incorrectly matched against parent main source-set (not test one)</li>
</ul>
<h3>IDE. Refactorings</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-24122"><code>KT-24122</code></a> Long pauses with &quot;removing redundant imports&quot; dialog on rename refactoring for IDEA Kotlin Plugin</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-32514"><code>KT-32514</code></a> Moving file in with 'search for references' inlines contents in referred source code</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-32999"><code>KT-32999</code></a> Renaming parameter does not rename usage in named argument in a different file</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-33372"><code>KT-33372</code></a> Rename resource cause its content to be replaced</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-34415"><code>KT-34415</code></a> Refactor &gt; Change signature of an overridden actual function from a platform class: &quot;org.jetbrains.kotlin.descriptors.InvalidModuleException: Accessing invalid module descriptor&quot;</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-34419"><code>KT-34419</code></a> Refactor &gt; Change signature &gt; add a function parameter: &quot;org.jetbrains.kotlin.descriptors.InvalidModuleException: Accessing invalid module descriptor&quot;</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-35689"><code>KT-35689</code></a> Change Signature:  &quot;InvalidModuleException: Accessing invalid module descriptor&quot; on attempt to change receiver type of a member abstract function</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-35903"><code>KT-35903</code></a> Change Signature refactoring crashes by InvalidModuleException on simplest examples</li>
</ul>
<h3>IDE. Run Configurations</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-35038"><code>KT-35038</code></a> Running a test in a multi-module MPP project via IntelliJ Idea gutter action produces incorrect Gradle Run configuration</li>
</ul>
<h3>Libraries</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-7657"><code>KT-7657</code></a> scan functions for Sequences and Iterable</li>
</ul>
</tr></table> ... (truncated)
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/JetBrains/kotlin/commit/9f2a5898c5ac457f6cfb67bacee8ee3227a1e0c1"><code>9f2a589</code></a> Update changelog (EAP 3)</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/62a0cd3d872e99c6f73255973ce84d14095404f4"><code>62a0cd3</code></a> Update K/N</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/89b75bb1589fc5ba88a7b1c14a86bb4ad595fc58"><code>89b75bb</code></a> Fix KT-36804 by eagerly instantiating the Kotlin/Native tasks</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/a0d64ea859127ddb905b159a4cf3007a53f5b6bb"><code>a0d64ea</code></a> Make 201 plugin compatible with IDEA trunk (KT-36780)</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/40e104ff1227d67e00dbe305c91fe7d392e8dcb2"><code>40e104f</code></a> Mark shared global vals to fix K/N worker thread crash</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/17e43f0c37a51d87a1600c7f6053d2bf0547acab"><code>17e43f0</code></a> Update K/N</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/f7c4afd00d61d6a6ad44f278d93df5a252cf09ea"><code>f7c4afd</code></a> Force-set path to exact project for MPP run configurations</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/f6685b30d6a66f86ac8730cad6920d04682907dc"><code>f6685b3</code></a> Fix requesting KotlinDslScriptModels for 191</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/de71c7bd06b28c31dfc22ff780815ada1e407748"><code>de71c7b</code></a> .gradle.kts: more clear tooltip for out of project scripts notification</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/4fe339c7b862ce7876126673c1e23b08a5397a74"><code>4fe339c</code></a> 201: Fix icon set in ShowFirAction.kt</li>
<li>Additional commits viewable in <a href="https://github.com/JetBrains/kotlin/compare/v1.3.70-eap-184...1.3.70-eap-274">compare view</a></li>
</ul>
</details>
<br />

Updates `kotlin-stdlib-jdk8` from 1.3.70-eap-184 to 1.3.70-eap-274
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/JetBrains/kotlin/releases">kotlin-stdlib-jdk8's releases</a>.</em></p>
<blockquote>
<h2>Kotlin 1.3.70 EAP 3</h2>
<h3>Compiler</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-31411"><code>KT-31411</code></a> Support mode of compiler where it analyses source-set as platform one, but produces only metadata for that specific source-set</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-32372"><code>KT-32372</code></a> Type inference errors in IDE</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-33542"><code>KT-33542</code></a> Compilation failed with &quot;AssertionError: Suspend functions may be called either as suspension points or from another suspend function&quot;</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-33544"><code>KT-33544</code></a> &quot;UnsupportedOperationException: no descriptor for type constructor of TypeVariable(R)?&quot; with BuilderInference and elvis operator</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-36297"><code>KT-36297</code></a> NI: ClassNotFoundException: compiler emits reference to nonexisting class for code with nested inline lambdas</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-36719"><code>KT-36719</code></a> Enable new inference in IDE since 1.3.70</li>
</ul>
<h3>IDE</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-33820"><code>KT-33820</code></a> Stop using com.intellij.codeInsight.AnnotationUtil#isJetbrainsAnnotation</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-33846"><code>KT-33846</code></a> Stop using com.intellij.openapi.vfs.newvfs.BulkFileListener.Adapter</li>
</ul>
<h3>IDE. Completion</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-36306"><code>KT-36306</code></a> Code completion inlines content of FQN class if completion called in string</li>
</ul>
<h3>IDE. Debugger</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-16277"><code>KT-16277</code></a> Can't set breakpoint for object construction</li>
</ul>
<h3>IDE. Inspections and Intentions</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-33771"><code>KT-33771</code></a> False positive &quot;Redundant Companion reference&quot; with Java synthetic property and same-named object property</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-36307"><code>KT-36307</code></a> False positive &quot;Remove redundant '.let' call&quot; for nested lambda change scope reference</li>
</ul>
<h3>IDE. Multiplatform</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-33321"><code>KT-33321</code></a> In IDE, actuals of intermediate test source set are incorrectly matched against parent main source-set (not test one)</li>
</ul>
<h3>IDE. Refactorings</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-24122"><code>KT-24122</code></a> Long pauses with &quot;removing redundant imports&quot; dialog on rename refactoring for IDEA Kotlin Plugin</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-32514"><code>KT-32514</code></a> Moving file in with 'search for references' inlines contents in referred source code</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-32999"><code>KT-32999</code></a> Renaming parameter does not rename usage in named argument in a different file</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-33372"><code>KT-33372</code></a> Rename resource cause its content to be replaced</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-34415"><code>KT-34415</code></a> Refactor &gt; Change signature of an overridden actual function from a platform class: &quot;org.jetbrains.kotlin.descriptors.InvalidModuleException: Accessing invalid module descriptor&quot;</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-34419"><code>KT-34419</code></a> Refactor &gt; Change signature &gt; add a function parameter: &quot;org.jetbrains.kotlin.descriptors.InvalidModuleException: Accessing invalid module descriptor&quot;</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-35689"><code>KT-35689</code></a> Change Signature:  &quot;InvalidModuleException: Accessing invalid module descriptor&quot; on attempt to change receiver type of a member abstract function</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-35903"><code>KT-35903</code></a> Change Signature refactoring crashes by InvalidModuleException on simplest examples</li>
</ul>
<h3>IDE. Run Configurations</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-35038"><code>KT-35038</code></a> Running a test in a multi-module MPP project via IntelliJ Idea gutter action produces incorrect Gradle Run configuration</li>
</ul>
<h3>Libraries</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-7657"><code>KT-7657</code></a> scan functions for Sequences and Iterable</li>
</ul>
</tr></table> ... (truncated)
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/JetBrains/kotlin/commit/9f2a5898c5ac457f6cfb67bacee8ee3227a1e0c1"><code>9f2a589</code></a> Update changelog (EAP 3)</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/62a0cd3d872e99c6f73255973ce84d14095404f4"><code>62a0cd3</code></a> Update K/N</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/89b75bb1589fc5ba88a7b1c14a86bb4ad595fc58"><code>89b75bb</code></a> Fix KT-36804 by eagerly instantiating the Kotlin/Native tasks</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/a0d64ea859127ddb905b159a4cf3007a53f5b6bb"><code>a0d64ea</code></a> Make 201 plugin compatible with IDEA trunk (KT-36780)</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/40e104ff1227d67e00dbe305c91fe7d392e8dcb2"><code>40e104f</code></a> Mark shared global vals to fix K/N worker thread crash</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/17e43f0c37a51d87a1600c7f6053d2bf0547acab"><code>17e43f0</code></a> Update K/N</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/f7c4afd00d61d6a6ad44f278d93df5a252cf09ea"><code>f7c4afd</code></a> Force-set path to exact project for MPP run configurations</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/f6685b30d6a66f86ac8730cad6920d04682907dc"><code>f6685b3</code></a> Fix requesting KotlinDslScriptModels for 191</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/de71c7bd06b28c31dfc22ff780815ada1e407748"><code>de71c7b</code></a> .gradle.kts: more clear tooltip for out of project scripts notification</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/4fe339c7b862ce7876126673c1e23b08a5397a74"><code>4fe339c</code></a> 201: Fix icon set in ShowFirAction.kt</li>
<li>Additional commits viewable in <a href="https://github.com/JetBrains/kotlin/compare/v1.3.70-eap-184...1.3.70-eap-274">compare view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)
- `@dependabot use these labels` will set the current labels as the default for future PRs for this repo and language
- `@dependabot use these reviewers` will set the current reviewers as the default for future PRs for this repo and language
- `@dependabot use these assignees` will set the current assignees as the default for future PRs for this repo and language
- `@dependabot use this milestone` will set the current milestone as the default for future PRs for this repo and language
- `@dependabot badge me` will comment on this PR with code to add a "Dependabot enabled" badge to your readme

Additionally, you can set the following in your Dependabot [dashboard](https://app.dependabot.com):
- Update frequency (including time of day and day of week)
- Pull request limits (per update run and/or open at any time)
- Out-of-range updates (receive only lockfile updates, if desired)
- Security updates (receive only security updates, if desired)



</details>